### ISSUE TITLE
Stubbing imports

### ISSUE THREAD

**Issue by djskinner** [eventualbuddha/rollup-plugin-stub#1]
Is it possible to use this plugin to stub `SomeMixin` in the following situation?

```
import React from 'react';
import SomeMixin from './SomeMixin';

const Component = React.createClass({
    mixins: [ SomeMixin ],
    render: function () {
        return (
            <div>
                ...
            </div>
        );
    }
});

export default Component;
```

**Comment by eventualbuddha** [comment]
Right now this plugin takes advantage of the nature of ES module bindings, but default exports do not use bindings. Therefore default exports cannot be stubbed with this plugin. I'll add a note to the README.
