### ISSUE TITLE
Error: Failed to process '...'

### ISSUE THREAD

**Issue by brianmhunt** [eventualbuddha/rollup-plugin-stub#2]
Using stub, I get an error: `Cannot read property 'type' of null`

I'm using rps in conjunction with rollup-plugin-node-resolve, but otherwise it's a very straightforward setup - was wondering if this is an issue you've seen.

**Comment by eventualbuddha** [comment]
Can you share your rollup config? It's much easier to reproduce the issue with a failing example.

**Comment by brianmhunt** [comment]
@eventualbuddha  No problem.  Instructions:
1. `git clone git@github.com:knockout/tko.utils.git`
2. `cd tko.utils`
3. `npm install`
4. `cd node_modules/tko-policy/`
5. `npm install --save rollup-plugin-stub`
6. Edit `tasks/test.js` and uncomment `stub()` on line 33
7. Go back to the `tko.utils` root and run `gulp test`.

You should a bunch of errors like this:

> 06 07 2016 08:01:20.712:ERROR [preprocessor.rollup]: Failed to process "/Users/bmh/tmp/tko.utils/src/css.js".
>   Error loading /Users/bmh/tmp/tko.utils/src/css.js: Cannot read property 'type' of null
> 
> 06 07 2016 08:01:20.869:ERROR [preprocessor.rollup]: Failed to process "/Users/bmh/tmp/tko.utils/src/ie.js".

I hope that helps!

**Comment by eventualbuddha** [comment]
Thanks! I'll check it out.

**Comment by patriknyblad** [comment]
This should be fixed in 1.1.1 👍
