### ISSUE TITLE
Stubbing imports (2)

### ISSUE THREAD

**Issue by joaovieira** [eventualbuddha/rollup-plugin-stub#6]
Say I want to test my Subject and mock an internal dependency, like so: 

```javascript
// dep.js
export function dep () {
  console.log('original')
}

// Subject.js
import { dep } from './dep'

export class Subject {
  myDep () {
    dep()
  }
}

// Subject.spec.js
import { Subject } from '../src/Subject'
import { stub_dep, reset_dep } from '../src/dep'

const spy = jasmine.createSpy('dep').and.callFake(() => console.log('mock'))
stub_dep(spy)

describe('Subject', () => {
  afterEach(reset_dep)

  it('myDep should call dep', () => {
    const sub = new Subject()
    sub.myDep()
    // expect to print 'mock'
    expect(spy).toHaveBeenCalled()
  })
})
```

Is this possible with this plugin? I've tried to play with it, invert imports. But the Subject will always use the original dependency.

Doing something like this http://stackoverflow.com/a/40267448 does work though. But I thought that's what the plugin was supposed to be doing.

**Comment by eventualbuddha** [comment]
What code does rollup generate?

**Comment by joaovieira** [comment]
Interesting, my simplified example works fine 😃  Let me have another look at the bigger picture and I'll let you know.

**Comment by joaovieira** [comment]
Ok. No problem now. Most probably, with all the playing around, I was exporting both named and default exports, using the default in Subject and trying to mock the named.

Closing. Thanks.

**Comment by joaovieira** [comment]
Nevertheless, I'd say this is the most common usage (stub an internal dependency), rather than mocking part of the module under test. What do you think? Worth updating the Readme example?
